name: Dhuir
favicon: null
layout_spectrum: 0.50658
typography_spectrum: 0.41227
title: 'Dhuir dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#88bdff'
    - '#fe9b0a'
    - '#051b8b'
    - '#6b6b6b'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
