name: Dhuir
favicon: null
layout_spectrum: 0
typography_spectrum: 0.150837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed068e'
    - '#0194d0'
    - '#ffbb31'
    - '#ffffff'
    - '#f0519f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
