name: Dhuir
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47564
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcc021'
    - '#f7d94f'
    - '#e5a215'
    - '#f0da9d'
    - '#fdedbc'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
