name: Dhuir
favicon: null
layout_spectrum: 0.37276
typography_spectrum: 0.86575
title: 'Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8da'
    - '#af986f'
    - '#ffffff'
    - '#3e463b'
    - '#201b1f'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
