analytics:
  google: UA-75147095-1
color:
  brandColors:
    - '#ed068e'
    - '#0194d0'
    - '#ffbb31'
    - '#ffffff'
    - '#f0519f'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.406424
name: Dhuir
opengraph: {}
purpose: []
typography_spectrum: 0.150837
