name: Dhuir
favicon: null
layout_spectrum: 0.6520326822064817
typography_spectrum: 0.06318415910936892
title: 'Dhuir, dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.15948942815884948
  lightness: 0.529468679567799
  saturation: 0.292806115699932
  rhythmicContrast: 0.3459579721093178
purpose: []
