analytics:
  google: UA-75147095-1
color:
  brandColors:
    - '#C0C0C0'
    - '#224962'
    - '#808080'
    - '#4088B8'
    - '#70A8C8'
  brandStrength: 0.4375
  lightness: 0.638268
  rhythmicContrast: 0.400838
  saturation: 0.72905
cta: {}
layout_spectrum: 0.206703
name: Dhuir
opengraph: {}
purpose: []
typography_spectrum: 0.389664
