name: Dhuir
favicon: null
layout_spectrum: 0.13800687459297478
typography_spectrum: 0.7470084642991424
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8601744277402759
  lightness: 0.0664881921838969
  saturation: 0.07537499000318348
  rhythmicContrast: 0.12956134811975062
purpose: []
