name: Dhuir
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39808
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001d6b'
    - '#f8f4eb'
    - '#d2b595'
    - '#0d6fac'
    - '#849479'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
