name: Dhuir
favicon: null
layout_spectrum: 0.45274
typography_spectrum: 0.389664
title: 'Dhuir, dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c9c9c9'
    - '#7f7f7f'
    - '#484848'
    - '#050505'
  brandStrength: 0.5625
  lightness: 0.638268
  saturation: 0.3125
  rhythmicContrast: 0.400838
purpose: []
