name: Dhuir
favicon: null
layout_spectrum: 0.25469
typography_spectrum: 0.4970932095311582
title: 'Dhuir, dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#77294b'
    - '#ffffff'
    - '#d1d2d4'
    - '#000000'
    - '#a77389'
  brandStrength: 0.375
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
