name: Dhuir
favicon: null
layout_spectrum: 0.22293
typography_spectrum: 0.41227
title: 'Dhuir - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0139a6'
    - '#d42b1e'
    - '#afafaf'
    - '#3854b5'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
