name: Dhuir
favicon: null
layout_spectrum: 0.13458
typography_spectrum: 0.7087
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff500'
    - '#e90000'
    - '#0068c7'
    - '#a8bd81'
    - '#452d22'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
