name: Dhuir
favicon: null
layout_spectrum: 0.70152
typography_spectrum: 0.83286
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff28c'
    - '#7d835d'
    - '#b3ab64'
    - '#04caac'
    - '#087860'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
