name: Dhuir
favicon: null
layout_spectrum: 0.4991
typography_spectrum: 0.86575
title: 'Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f0e3'
    - '#b3b5a8'
    - '#696772'
    - '#3f354e'
    - '#19061c'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
