name: Dhuir
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86575
title: 'Dhuir - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7ea8c1'
    - '#000000'
    - '#d7bcb3'
    - '#4b4358'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
