name: Dhuir
favicon: null
layout_spectrum: 0.25294
typography_spectrum: 0.389664
title: 'Dhuir, dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#df0100'
    - '#b0b0b0'
    - '#646464'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
