name: Dhuir
favicon: null
layout_spectrum: 0.23218
typography_spectrum: 0.150837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ba683d'
    - '#2f2f2f'
    - '#f8bd00'
    - '#bc1a1e'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
