name: Dhuir
favicon: null
layout_spectrum: 0.25294
typography_spectrum: 0.81423
title: 'Dhuir, dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#77294b'
    - '#ffffff'
    - '#d1d2d4'
    - '#000000'
    - '#a77389'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
