name: Dhuir
favicon: null
layout_spectrum: 0.23385
typography_spectrum: 0.12607
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd8000'
    - '#fdd303'
    - '#f9f679'
    - '#fcfcef'
    - '#ffbb45'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
