name: Dhuir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.150837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7d4e24'
    - '#94c11c'
    - '#040404'
    - '#1d9ca8'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
