name: Dhuir
favicon: null
layout_spectrum: 0.00214
typography_spectrum: 0.38543
title: 'DHUIR - Dejar de tener miedo, empezar a tener Fe'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1b8'
    - '#a42d25'
    - '#afaaa7'
    - '#2f2822'
    - '#7e7a5a'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
