layout_spectrum: 0.9800574756227434
typography_spectrum: 0.5104466129560024
color:
  brandColors:
    - '#FFFFFF'
    - '#283F85'
    - '#F3931B'
    - '#E7192D'
    - '#0198D1'
  brandStrength: 0.4489579414948821
  lightness: 0.6024079679045826
  saturation: 0.4267650740221143
  rhythmicContrast: 0.6090919349808246
coverPrefs:
  filter: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-75147095-1
  facebook: null
  twitter: null
author:
  name: Alejandro Rojas
  email: alejandro.kiho@gmail.com
  url: www.dhuir.cl
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9d6ebf9f-85b6-4d38-8f38-419c37323ba0.jpg
name: Dhuir
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Que es Duir y de donde procede
    id: 97b838bb-8618-4231-a826-061aa22cd2ec
    type: content
  - name: ¿Por qué Ki-Ho?
    id: 32d2de93-c488-422f-87a9-a62ceb2c7ed6
    type: content
  - name: Reiki Usui Ki Ho
    id: b8dd7b1b-4179-4c2c-8c2b-8d2e253439c1
    type: content
  - name: Niveles del Reiki Usui Ki Ho
    id: 0ebed4dd-8e3a-4266-8a65-91f3fd62c9cf
    type: content
  - name: Medalla de San Benito
    id: 2e4316d3-e4fd-42d6-9c00-76e0f8c09211
    type: content
  - name: dhuir
    url: www.dhuir.cl
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/83245100-bd7d-4c56-b78e-6fc19db2eaf6.jpg
title: 'Dhuir, dejar de tener miedo, empezar a tener Fe'
purpose: []
